In [ ]:
# Questão 1

import pandas as pd
df_imoveis = pd.read_csv("imoveis_aluguel.csv", index_col=0)
display(df_imoveis.head())

,Titulo_Anuncio,Bairro,Tipo_Propriedade,Quartos,Valor_Diaria,Taxa_Limpeza,Nota_Avaliacao
ID_Imovel,,,,,,,
1,apto vista mar,Copacabana,Apartamento,2,450.0,150.0,4.8
2,COBERTURA DE LUXO,Ipanema,Cobertura,4,1500.0,300.0,4.9
3,Studio central,NaN,Studio,1,200.0,80.0,4.5
4,casa com piscina,Barra da Tijuca,Casa,3,800.0,200.0,4.7
5,Lindo Apto 2 quartos,Copacabana,Apartamento,2,350.0,120.0,NaN

In [ ]:
# Questão 2

display(df_imoveis.iloc[6:12])

,Titulo_Anuncio,Bairro,Tipo_Propriedade,Quartos,Valor_Diaria,Taxa_Limpeza,Nota_Avaliacao
ID_Imovel,,,,,,,
7,cobertura espetacular,Leblon,Cobertura,3,1800.0,350.0,5.0
8,Apto Aconchegante,NaN,Apartamento,1,180.0,70.0,4.3
9,CASA PRAIA,Barra da Tijuca,Casa,4,1200.0,250.0,4.8
10,studio economico,Centro,Studio,1,120.0,50.0,4.0
11,Apto Frente Mar,Ipanema,Apartamento,3,900.0,200.0,NaN
12,cobertura duplex,Botafogo,Cobertura,3,1100.0,250.0,4.7

In [82]:
# Questão 3

df_imoveis["Titulo_Anuncio"] = df_imoveis["Titulo_Anuncio"].str.upper()
df_imoveis["Titulo_Anuncio"].head()

ID_Imovel
1          APTO VISTA MAR
2       COBERTURA DE LUXO
3          STUDIO CENTRAL
4        CASA COM PISCINA
5    LINDO APTO 2 QUARTOS
Name: Titulo_Anuncio, dtype: str

In [ ]:
# Questão 4

df_imoveis[df_imoveis["Titulo_Anuncio"].str.contains("COBERTURA")]

,Titulo_Anuncio,Bairro,Tipo_Propriedade,Quartos,Valor_Diaria,Taxa_Limpeza,Nota_Avaliacao
ID_Imovel,,,,,,,
2,COBERTURA DE LUXO,Ipanema,Cobertura,4,1500.0,300.0,4.9
7,COBERTURA ESPETACULAR,Leblon,Cobertura,3,1800.0,350.0,5.0
12,COBERTURA DUPLEX,Botafogo,Cobertura,3,1100.0,250.0,4.7
16,COBERTURA VISTA LAGOA,Leblon,Cobertura,4,2000.0,400.0,5.0
20,COBERTURA CHARMOSA,Copacabana,Cobertura,2,950.0,200.0,4.7
24,COBERTURA BARRA,Barra da Tijuca,Cobertura,4,1700.0,350.0,NaN
28,COBERTURA IPANEMA,NaN,Cobertura,3,1600.0,300.0,4.9
32,COBERTURA CENTRO,Centro,Cobertura,2,600.0,150.0,4.3
36,COBERTURA INCRIVEL,Barra da Tijuca,Cobertura,5,2200.0,400.0,4.9
40,COBERTURA BOTAFOGO,NaN,Cobertura,3,1300.0,250.0,4.8
44,COBERTURA PANORAMICA,Copacabana,Cobertura,4,1900.0,350.0,NaN
48,COBERTURA SOLARIUM,Leblon,Cobertura,3,1700.0,300.0,4.9
52,COBERTURA VINTAGE,Lapa,Cobertura,2,700.0,180.0,4.5
56,COBERTURA COM PISCINA,Recreio,Cobertura,4,1500.0,300.0,4.9
60,COBERTURA MINIMALISTA,Copacabana,Cobertura,2,1000.0,220.0,4.8
64,COBERTURA LESTE,Ipanema,Cobertura,3,1550.0,300.0,4.9
68,COBERTURA DUPLEX CENTRO,Centro,Cobertura,2,800.0,200.0,4.4
72,COBERTURA SUL,Leblon,Cobertura,4,2100.0,400.0,5.0
76,COBERTURA PREMIUM,NaN,Cobertura,5,2800.0,500.0,4.9
80,COBERTURA MODERNA,Botafogo,Cobertura,3,1400.0,250.0,4.7
84,COBERTURA IPANEMA 2,Ipanema,Cobertura,3,1650.0,300.0,NaN
88,COBERTURA NORTE,NaN,Cobertura,2,900.0,200.0,4.6
92,COBERTURA OESTE,Barra da Tijuca,Cobertura,4,1800.0,350.0,4.9
96,COBERTURA SUL 2,Leblon,Cobertura,3,1750.0,320.0,NaN

In [ ]:
# Questão 5

df_imoveis[df_imoveis["Tipo_Propriedade"] == "Apartamento"]
df_imoveis[df_imoveis["Quartos"] >= 3]

,Titulo_Anuncio,Bairro,Tipo_Propriedade,Quartos,Valor_Diaria,Taxa_Limpeza,Nota_Avaliacao
ID_Imovel,,,,,,,
2,COBERTURA DE LUXO,Ipanema,Cobertura,4,1500.0,300.0,4.9
4,CASA COM PISCINA,Barra da Tijuca,Casa,3,800.0,200.0,4.7
7,COBERTURA ESPETACULAR,Leblon,Cobertura,3,1800.0,350.0,5.0
9,CASA PRAIA,Barra da Tijuca,Casa,4,1200.0,250.0,4.8
11,APTO FRENTE MAR,Ipanema,Apartamento,3,900.0,200.0,NaN
12,COBERTURA DUPLEX,Botafogo,Cobertura,3,1100.0,250.0,4.7
16,COBERTURA VISTA LAGOA,Leblon,Cobertura,4,2000.0,400.0,5.0
17,CASA ESPAÇOSA,Barra da Tijuca,Casa,5,1500.0,300.0,4.9
19,APTO FAMILIA,Ipanema,Apartamento,3,850.0,180.0,4.8
21,CASA DE CAMPO,NaN,Casa,3,600.0,150.0,4.5
24,COBERTURA BARRA,Barra da Tijuca,Cobertura,4,1700.0,350.0,NaN
25,CASA TEMPORADA,Recreio,Casa,4,900.0,200.0,4.7
28,COBERTURA IPANEMA,NaN,Cobertura,3,1600.0,300.0,4.9
29,CASA LUXO,Leblon,Casa,5,2500.0,500.0,5.0
33,CASA AMPLA,NaN,Casa,3,750.0,180.0,4.6
36,COBERTURA INCRIVEL,Barra da Tijuca,Cobertura,5,2200.0,400.0,4.9
37,CASA RECREIO,Recreio,Casa,3,700.0,150.0,4.6
40,COBERTURA BOTAFOGO,NaN,Cobertura,3,1300.0,250.0,4.8
41,CASA VERDE,Barra da Tijuca,Casa,4,1100.0,200.0,4.7
44,COBERTURA PANORAMICA,Copacabana,Cobertura,4,1900.0,350.0,NaN
47,APTO ESPACOSO,Barra da Tijuca,Apartamento,4,900.0,220.0,4.7
48,COBERTURA SOLARIUM,Leblon,Cobertura,3,1700.0,300.0,4.9
49,CASA HISTÓRICA,Centro,Casa,3,550.0,150.0,4.4
53,CASA CONDOMINIO,Barra da Tijuca,Casa,5,1800.0,400.0,4.8
55,APTO FAMILIAR,Ipanema,Apartamento,3,800.0,180.0,4.7
56,COBERTURA COM PISCINA,Recreio,Cobertura,4,1500.0,300.0,4.9
57,CASA BEIRA MAR,NaN,Casa,4,2000.0,450.0,5.0
59,APTO VARANDA GOURMET,Leblon,Apartamento,3,1100.0,250.0,NaN
61,CASA DE PRAIA,Recreio,Casa,3,850.0,180.0,4.6
64,COBERTURA LESTE,Ipanema,Cobertura,3,1550.0,300.0,4.9
65,CASA TRIPLEX,Barra da Tijuca,Casa,5,2100.0,400.0,NaN
67,APTO CLASSICO,Copacabana,Apartamento,3,750.0,180.0,4.6
72,COBERTURA SUL,Leblon,Cobertura,4,2100.0,400.0,5.0
73,CASA DE CAMPO 2,Jacarepagua,Casa,3,500.0,150.0,4.3
76,COBERTURA PREMIUM,NaN,Cobertura,5,2800.0,500.0,4.9
77,CASA DOS SONHOS,Barra da Tijuca,Casa,5,3000.0,600.0,5.0
80,COBERTURA MODERNA,Botafogo,Cobertura,3,1400.0,250.0,4.7
81,CASA GEMINADA,Recreio,Casa,3,650.0,150.0,4.5
83,APTO ESPACO,NaN,Apartamento,4,1000.0,250.0,4.6
84,COBERTURA IPANEMA 2,Ipanema,Cobertura,3,1650.0,300.0,NaN
85,CASA CONDOMINIO 2,Barra da Tijuca,Casa,4,1600.0,300.0,4.8
91,APTO 3 QTOS,Copacabana,Apartamento,3,650.0,160.0,4.7
92,COBERTURA OESTE,Barra da Tijuca,Cobertura,4,1800.0,350.0,4.9
93,CASA BARRA,Barra da Tijuca,Casa,3,950.0,200.0,4.6
95,APTO LUXO,NaN,Apartamento,4,1500.0,300.0,4.9
96,COBERTURA SUL 2,Leblon,Cobertura,3,1750.0,320.0,NaN
97,CASA COLONIAL,Centro,Casa,4,800.0,200.0,4.4
19,APTO FAMILIA,Ipanema,Apartamento,3,850.0,180.0,4.8
81,CASA GEMINADA,Recreio,Casa,3,650.0,150.0,4.5

In [ ]:
# Questão 6

df_imoveis[df_imoveis["Bairro"].isin(["Copacabana", "Leblon"])]

,Titulo_Anuncio,Bairro,Tipo_Propriedade,Quartos,Valor_Diaria,Taxa_Limpeza,Nota_Avaliacao
ID_Imovel,,,,,,,
1,APTO VISTA MAR,Copacabana,Apartamento,2,450.0,150.0,4.8
5,LINDO APTO 2 QUARTOS,Copacabana,Apartamento,2,350.0,120.0,NaN
7,COBERTURA ESPETACULAR,Leblon,Cobertura,3,1800.0,350.0,5.0
15,APTO REFORMADO,Copacabana,Apartamento,2,380.0,130.0,4.6
16,COBERTURA VISTA LAGOA,Leblon,Cobertura,4,2000.0,400.0,5.0
20,COBERTURA CHARMOSA,Copacabana,Cobertura,2,950.0,200.0,4.7
23,APTO SOL DA MANHA,Leblon,Apartamento,2,550.0,150.0,4.9
29,CASA LUXO,Leblon,Casa,5,2500.0,500.0,5.0
31,APTO 1 QUARTO,Copacabana,Apartamento,1,200.0,80.0,NaN
34,STUDIO COPACABANA,Copacabana,Studio,1,240.0,90.0,4.5
39,APTO DESIGN,Leblon,Apartamento,2,650.0,160.0,4.9
44,COBERTURA PANORAMICA,Copacabana,Cobertura,4,1900.0,350.0,NaN
48,COBERTURA SOLARIUM,Leblon,Cobertura,3,1700.0,300.0,4.9
50,STUDIO VARANDA,Copacabana,Studio,1,260.0,90.0,4.6
59,APTO VARANDA GOURMET,Leblon,Apartamento,3,1100.0,250.0,NaN
60,COBERTURA MINIMALISTA,Copacabana,Cobertura,2,1000.0,220.0,4.8
67,APTO CLASSICO,Copacabana,Apartamento,3,750.0,180.0,4.6
72,COBERTURA SUL,Leblon,Cobertura,4,2100.0,400.0,5.0
78,STUDIO VISTA MAR,Copacabana,Studio,1,320.0,100.0,NaN
79,APTO LINDO,Leblon,Apartamento,2,600.0,150.0,4.8
91,APTO 3 QTOS,Copacabana,Apartamento,3,650.0,160.0,4.7
94,STUDIO COMPACTO 2,Copacabana,Studio,1,230.0,80.0,4.5
96,COBERTURA SUL 2,Leblon,Cobertura,3,1750.0,320.0,NaN

In [ ]:
# Questão 7

df_imoveis["Custo_Total_Dia"] = df_imoveis["Valor_Diaria"] + df_imoveis["Taxa_Limpeza"]
df_imoveis.head()

,Titulo_Anuncio,Bairro,Tipo_Propriedade,Quartos,Valor_Diaria,Taxa_Limpeza,Nota_Avaliacao,Custo_Total_Dia
ID_Imovel,,,,,,,,
1,apto vista mar,Copacabana,Apartamento,2,450.0,150.0,4.8,600.0
2,COBERTURA DE LUXO,Ipanema,Cobertura,4,1500.0,300.0,4.9,1800.0
3,Studio central,NaN,Studio,1,200.0,80.0,4.5,280.0
4,casa com piscina,Barra da Tijuca,Casa,3,800.0,200.0,4.7,1000.0
5,Lindo Apto 2 quartos,Copacabana,Apartamento,2,350.0,120.0,NaN,470.0

In [ ]:
# Questão 8

df_imoveis.loc[df_imoveis["Bairro"] == "Centro", "Taxa_Limpeza"] = df_imoveis.loc[df_imoveis["Bairro"] == "Centro", "Taxa_Limpeza"] - 20.0
df_imoveis[df_imoveis["Bairro"] == "Centro"]

,Titulo_Anuncio,Bairro,Tipo_Propriedade,Quartos,Valor_Diaria,Taxa_Limpeza,Nota_Avaliacao,Custo_Total_Dia
ID_Imovel,,,,,,,,
10,studio economico,Centro,Studio,1,120.0,10.0,4.0,170.0
18,studio executivo,Centro,Studio,1,160.0,30.0,NaN,230.0
26,studio wifi rapido,Centro,Studio,1,130.0,10.0,4.1,180.0
32,Cobertura Centro,Centro,Cobertura,2,600.0,110.0,4.3,750.0
42,STUDIO COMPACTO,Centro,Studio,1,90.0,0.0,3.9,130.0
49,Casa Histórica,Centro,Casa,3,550.0,110.0,4.4,700.0
58,studio executivo 2,Centro,Studio,1,170.0,20.0,4.2,230.0
68,cobertura duplex centro,Centro,Cobertura,2,800.0,160.0,4.4,1000.0
74,Studio Work,Centro,Studio,1,140.0,10.0,4.1,190.0
89,casa centro,Centro,Casa,2,400.0,60.0,4.2,500.0
90,studio centro 2,Centro,Studio,1,100.0,10.0,NaN,150.0
97,casa colonial,Centro,Casa,4,800.0,160.0,4.4,1000.0

In [ ]:
# Questão 9

df_imoveis[df_imoveis["Nota_Avaliacao"].notnull()]

,Titulo_Anuncio,Bairro,Tipo_Propriedade,Quartos,Valor_Diaria,Taxa_Limpeza,Nota_Avaliacao,Custo_Total_Dia
ID_Imovel,,,,,,,,
1,APTO VISTA MAR,Copacabana,Apartamento,2,450.0,150.0,4.8,600.0
2,COBERTURA DE LUXO,Ipanema,Cobertura,4,1500.0,300.0,4.9,1800.0
3,STUDIO CENTRAL,NaN,Studio,1,200.0,80.0,4.5,280.0
4,CASA COM PISCINA,Barra da Tijuca,Casa,3,800.0,200.0,4.7,1000.0
6,STUDIO MODERNO,Botafogo,Studio,1,250.0,90.0,4.6,340.0
...,...,...,...,...,...,...,...,...
95,APTO LUXO,NaN,Apartamento,4,1500.0,300.0,4.9,1800.0
97,CASA COLONIAL,Centro,Casa,4,800.0,160.0,4.4,1000.0
6,STUDIO MODERNO,Botafogo,Studio,1,250.0,90.0,4.6,340.0
19,APTO FAMILIA,Ipanema,Apartamento,3,850.0,180.0,4.8,1030.0
81,CASA GEMINADA,Recreio,Casa,3,650.0,150.0,4.5,800.0

In [83]:
# Questão 10

df_imoveis.loc[20:25, ['Bairro', 'Tipo_Propriedade', 'Valor_Diaria']]

                    Bairro Tipo_Propriedade  Valor_Diaria
ID_Imovel
20              Copacabana        Cobertura         950.0
21                     NaN             Casa         600.0
22                Botafogo           Studio         220.0
23                  Leblon      Apartamento         550.0
24         Barra da Tijuca        Cobertura        1700.0
25                 Recreio             Casa         900.0