In [6]:
import pandas as pd
import numpy as np

In [7]:
dados_catalogo = {
"ID_Titulo": [101, 102, 103, 104, 105, 106, 101, 107, 108],
"Titulo": ["Stranger Things", "O Poderoso Chefão", "Interestelar",
"Breaking Bad", "Duna", "Succession", "Stranger Things", "Toy Story",
"Vingadores: Ultimato"],
"Tipo": ["Série", "Filme", "Filme", "Série", "Filme", "Série", "Série",
"Filme", "Filme"],
"Ano": [2016, 1972, np.nan, 2008, 2021, 2018, 2016, 1995, 2019],
"Genero": ["Ficção Científica", np.nan, "Ficção Científica", "Drama",
"Ficção Científica", "Drama", "Ficção Científica", "Animação", "Ação"],
"Plataforma": ["Netflix", "Prime Video", "Prime Video", "Netflix", "HBOMax", "HBO Max", "Netflix", "Disney+", "Disney+"]
}
df_catalogo = pd.DataFrame(dados_catalogo)

In [10]:
dados_metricas = {
"ID_Titulo": [101, 102, 103, 104, 105, 106, 107, 109], # O ID 109 é de um filme que não está no catálogo
"Nota_IMDb": [8.7, 9.2, 8.6, 9.5, 8.0, 8.8, 8.3, 9.0],
"Votos_Milhares": [1200, 1900, 1500, 1800, 700, 450, 600, 950],
"Orcamento_Milhoes": [12.0, 6.0, 165.0, 3.0, 165.0, 9.0, 30.0, 180.0]
}
df_metricas = pd.DataFrame(dados_metricas)
print("Tabelas carregadas com sucesso! Pronto para iniciar a análise.")

Tabelas carregadas com sucesso! Pronto para iniciar a análise.

In [12]:
duplicadas = df_catalogo.duplicated().sum()
print(duplicadas)

df_catalogo = df_catalogo.drop_duplicates().reset_index(drop=True)
df_catalogo["Genero"] = df_catalogo["Genero"].fillna("Clássico")
df_catalogo.loc[df_catalogo["Titulo"] == "Interestelar", "Ano"] = 2014

print(df_catalogo.isnull().sum())

1
ID_Titulo     0
Titulo        0
Tipo          0
Ano           0
Genero        0
Plataforma    0
dtype: int64

In [13]:
display(df_catalogo.loc[:2, ["Titulo", "Plataforma"]])

print(df_catalogo.loc[4, "Titulo"])

filtro = df_catalogo[
    (df_catalogo["Genero"] == "Ficção Científica") &
    (df_catalogo["Ano"] >= 2015)
]

display(filtro)

def categoria_orcamento(valor):
    if valor < 10:
        return "Baixo Custo"
    elif valor < 100:
        return "Médio Custo"
    else:
        return "Blockbuster"

              Titulo   Plataforma
0    Stranger Things      Netflix
1  O Poderoso Chefão  Prime Video
2       Interestelar  Prime Video

Duna

   ID_Titulo           Titulo   Tipo     Ano             Genero Plataforma
0        101  Stranger Things  Série  2016.0  Ficção Científica    Netflix
4        105             Duna  Filme  2021.0  Ficção Científica     HBOMax

In [14]:
df_consolidado = pd.merge(df_catalogo, df_metricas, on="ID_Titulo", how="left")
display(df_consolidado)

,ID_Titulo,Titulo,Tipo,Ano,Genero,Plataforma,Nota_IMDb,Votos_Milhares,Orcamento_Milhoes
0,101,Stranger Things,Série,2016.0,Ficção Científica,Netflix,8.7,1200.0,12.0
1,102,O Poderoso Chefão,Filme,1972.0,Clássico,Prime Video,9.2,1900.0,6.0
2,103,Interestelar,Filme,2014.0,Ficção Científica,Prime Video,8.6,1500.0,165.0
3,104,Breaking Bad,Série,2008.0,Drama,Netflix,9.5,1800.0,3.0
4,105,Duna,Filme,2021.0,Ficção Científica,HBOMax,8.0,700.0,165.0
5,106,Succession,Série,2018.0,Drama,HBO Max,8.8,450.0,9.0
6,107,Toy Story,Filme,1995.0,Animação,Disney+,8.3,600.0,30.0
7,108,Vingadores: Ultimato,Filme,2019.0,Ação,Disney+,NaN,NaN,NaN

In [17]:
media_nota = df_consolidado["Nota_IMDb"].mean()
media_votos = df_consolidado["Votos_Milhares"].mean()

df_consolidado["Nota_IMDb"] = df_consolidado["Nota_IMDb"].fillna(media_nota)
df_consolidado["Votos_Milhares"] = df_consolidado["Votos_Milhares"].fillna(media_votos)
df_consolidado["Orcamento_Milhoes"] = df_consolidado["Orcamento_Milhoes"].fillna(0.0)

display(df_consolidado)

,ID_Titulo,Titulo,Tipo,Ano,Genero,Plataforma,Nota_IMDb,Votos_Milhares,Orcamento_Milhoes
0,101,Stranger Things,Série,2016.0,Ficção Científica,Netflix,8.700000,1200.000000,12.0
1,102,O Poderoso Chefão,Filme,1972.0,Clássico,Prime Video,9.200000,1900.000000,6.0
2,103,Interestelar,Filme,2014.0,Ficção Científica,Prime Video,8.600000,1500.000000,165.0
3,104,Breaking Bad,Série,2008.0,Drama,Netflix,9.500000,1800.000000,3.0
4,105,Duna,Filme,2021.0,Ficção Científica,HBOMax,8.000000,700.000000,165.0
5,106,Succession,Série,2018.0,Drama,HBO Max,8.800000,450.000000,9.0
6,107,Toy Story,Filme,1995.0,Animação,Disney+,8.300000,600.000000,30.0
7,108,Vingadores: Ultimato,Filme,2019.0,Ação,Disney+,8.728571,1164.285714,0.0

In [28]:
agrupamento_genero = df_consolidado.groupby("Genero")
display(agrupamento_genero)

soma = agrupamento_genero["Orcamento_Milhoes"].sum()
media = agrupamento_genero["Nota_IMDb"].mean()

print(soma)
print(media)
print(agrupamento_genero["Orcamento_Milhoes"].sum().idxmax())
print(agrupamento_genero["Nota_IMDb"].mean().idxmax())

Genero
Animação              30.0
Ação                   0.0
Clássico               6.0
Drama                 12.0
Ficção Científica    342.0
Name: Orcamento_Milhoes, dtype: float64
Genero
Animação             8.300000
Ação                 8.728571
Clássico             9.200000
Drama                9.150000
Ficção Científica    8.433333
Name: Nota_IMDb, dtype: float64
Ficção Científica
Clássico

In [18]:
df_consolidado["Perfil_Financeiro"] = df_consolidado["Orcamento_Milhoes"].apply(categoria_orcamento)

display(df_consolidado)

,ID_Titulo,Titulo,Tipo,Ano,Genero,Plataforma,Nota_IMDb,Votos_Milhares,Orcamento_Milhoes,Perfil_Financeiro
0,101,Stranger Things,Série,2016.0,Ficção Científica,Netflix,8.700000,1200.000000,12.0,Médio Custo
1,102,O Poderoso Chefão,Filme,1972.0,Clássico,Prime Video,9.200000,1900.000000,6.0,Baixo Custo
2,103,Interestelar,Filme,2014.0,Ficção Científica,Prime Video,8.600000,1500.000000,165.0,Blockbuster
3,104,Breaking Bad,Série,2008.0,Drama,Netflix,9.500000,1800.000000,3.0,Baixo Custo
4,105,Duna,Filme,2021.0,Ficção Científica,HBOMax,8.000000,700.000000,165.0,Blockbuster
5,106,Succession,Série,2018.0,Drama,HBO Max,8.800000,450.000000,9.0,Baixo Custo
6,107,Toy Story,Filme,1995.0,Animação,Disney+,8.300000,600.000000,30.0,Médio Custo
7,108,Vingadores: Ultimato,Filme,2019.0,Ação,Disney+,8.728571,1164.285714,0.0,Baixo Custo